
version: 1

root:
  level: DEBUG
  handlers: [console]

loggers:
  # some loggers in third party libraries may not have a loglevel at all.
  ats:
    level: DEBUG
  aiohttp:
    level: DEBUG

handlers:
  console:
    class: logging.StreamHandler
    formatter: colored
    level: DEBUG
    stream: ext://sys.stdout

formatters:
  colored:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(asctime)s - %(name)s - %(levelname)-8s%(reset)s %(message_log_color)s%(message)s"
    secondary_log_colors:
      message:
        ERROR: "red"
        CRITICAL: "red"

